version: "3"
services:
  notebook:
    image: jupyter/datascience-notebook
    ports:
      - "8887:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./src:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''