version: "3.9"
services:
  notebook:
    container_name: jupyterlab
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8887:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./src:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''