FROM nginx:1.19.6

ADD ./nginx/nginx.conf /etc/nginx/nginx.conf
ADD ./nginx/default.conf /etc/nginx/sites-available/default
ADD ./nginx/default.conf /etc/nginx/sites-enabled/default
ADD ./nginx/uwsgi_params /etc/nginx/uwsgi_params

RUN mkdir /var/www
RUN mkdir /var/www/front
RUN mkdir /var/www/static