version: '3'
services:
  nginx:
    build:
      context: ./
      dockerfile: ./Dockerfile-nginx
    environment:
      TZ: 'Asia/Tokyo'
    ports:
      - 8000:8000
    volumes:
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./aiapp/static:/var/www/static/
      - ./nginx:/var/log/nginx
    depends_on:
      - django

  # vue:
  #   build:
  #     context: .
  #     dockerfile: "./Dockerfile-nodejs"
  #   volumes:
  #     - ./front/ai-project:/app/ai-project/:cached
  #     - ./front/node_modules:/app/node_modules
  #   ports:
  #     - "8080:8080"
  #   command: npm run serve

  django:
    build:
      context: .
      dockerfile: "./Dockerfile-django"
    volumes:
      - .:/code
    # expose:
    #   - "8001"
    ports:
      - "8001:8001"
    ports:
      - "8010:8010"
    depends_on:
      - postgres
    command: 'sh ./start_django.sh'

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"